### PR TITLE
Slurm Exposed REST API 

### PR DESCRIPTION
**Pull request by lanced00m**
Hi, for connecting: https://github.com/google/tsunami-security-scanner-plugins/issues/423
https://github.com/google/tsunami-security-scanner-plugins/pull/496

### CODE REVIEW

**Comment by lokiuox** [comment]
Hi @lanced00m,

Thank you for your contribution! I'm reviewing your submission, but unfortunately this testbed is too complex and not self-contained, which makes it difficult and time-consuming to set up every time the plugin would need to be tested. Moreover, it requires a specific Ubuntu version and several modifications to the host system, whereas testbeds are usually set up in an isolated environment.

Could you please change the testbed so that it can be easily deployed (e.g. through docker-compose) without needing a specific host OS or modifications to the host?

I tried to do a quick web search for self-contained Slurm projects for testing purposes, and I found the following. You could check whether any of these could work as a testbed.
- https://github.com/SciDAS/slurm-in-docker
- https://github.com/giovtorres/slurm-docker-cluster
- https://medium.com/analytics-vidhya/slurm-cluster-with-docker-9f242deee601
- https://hub.docker.com/r/giovtorres/slurm-docker-cluster
- https://codebase.helmholtz.cloud/fwcc/slurm-in-docker

If it's not possible to change the testbed, I'd ask you to please submit a VM image too (preferably in .ova format) with the environment already set up, which can be just launched and scanned with Tsunami.

**Comment by lanced00m** [comment]
Hi @lokiuox 
I tried hard before to utilize nearly all of the public slurm setup instructions, but the problem is that all of these have some bugs. Finally, I managed to set up a good slurm with docker-compose from the slurm Gitlab repository itself and you are right about the setup issue that it takes too long to be ready for testing.

I spun up an Ubuntu instance now but the size of the ".ova" file is huge and I'm not sure if I'm able to upload such a huge file :)

My suggestion is that I set up an online instance exclusively for the test for one month or more and give you access using the same setup I introduced here.

I'm not sure if I can upload 30GB ".ova" file with my current internet connection lol

**Comment by lokiuox** [comment]
Ok, I see. Unfortunately a temporary instance is not ideal as we need a setup that can be reproduced whenever we need to test the plugin. Maybe you could try to reduce the .ova size, for example by using an ubuntu server image with no graphical interface. I see that this testbed also includes a lot of extra services (such as grafana, influxdb, sql_server, etc), could it be possible to remove these and just have the core slurm software running? I guess this would also reduce the size quite a bit.

If it's still too big for you to upload, I could take a deeper look at this in a few weeks and see if there is a solution.

**Comment by lanced00m** [comment]
@lokiuox I tried to accelerate the testbed setup, so far so good and it has still some work to be finished.

**Comment by lanced00m** [comment]
I'm pushing the docker images to my GitHub docker registry and Also I disabled all extra compute nodes and xdmod. other services like the logging services are not time-consuming during the setup comparing the core services.

**Comment by lanced00m** [comment]
Hi, unfortunately, the docker registry solution didn't work, so I sent the OVA file to you right now. note that I spun up the machine exactly according the this testbed.

**Comment by lanced00m** [comment]
@lokiuox thank you a lot!

**Pull request closed without merging**
